# docker compose up -d

services:
  api:
    container_name: rsa_system_api
    build:
      context: .
      dockerfile: docker/java/Dockerfile
    ports:
      - "${DOCKER_API_PORT:-8081}:8081"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2 # Maven cache
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - rsa_system
    restart: unless-stopped
  mysql:
    container_name: rsa_system_mysql
    image: mysql:8.0
    ports:
      - "${DOCKER_MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      TZ: "UTC"
    volumes:
      - rsa_system_mysql_data:/var/lib/mysql
      - ./docker/mysql/conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rsa_system
  phpmyadmin:
    container_name: rsa_system_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "${DOCKER_PMA_PORT:-8080}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - rsa_system
volumes:
  rsa_system_mysql_data:
networks:
  rsa_system:
    driver: bridge
